#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate per-engine token files from the canonical brand.yml.

Usage:
    tools/tokens.py [brand.yml] [outdir]
    tools/tokens.py --check

Reads _extensions/obsidian/brand.yml (the single source of truth for
palette, type and spacing) and writes:

    tokens.tex    \\definecolor{...}{HTML}{...} lines for LaTeX
    tokens.scss   $token-... / $type-... / $space-... variables

The generator is deliberately small: brand.yml uses a flat YAML
subset (section headers, then `key: value` lines with quoted
strings or inline lists), which the parser below handles without a
YAML dependency. The house palette must not change; the neutral
swatches are opt-in accents.

Legacy house names (obsidian, obsidianl, obsidianlink, ruled,
cream) are aliased to their semantic roles so existing .tex files
keep working unchanged.

--check verifies the light theme's literal values still match the
semantic roles in brand.yml (Quarto evaluates the theme defaults
section before file-level imports, so the theme keeps literals and
a drift guard keeps them honest).
"""

import re
import sys
from pathlib import Path

LEGACY_ALIASES = {
    "obsidian": "primary",
    "obsidianl": "secondary",
    "obsidianlink": "link",
    "ruled": "border",
    "cream": "surface",
}


def _strip_comment(line: str) -> str:
    """Remove a trailing comment, keeping # inside quoted values."""
    in_quote = False
    for i, ch in enumerate(line):
        if ch == '"':
            in_quote = not in_quote
        elif ch == "#" and not in_quote:
            return line[:i]
    return line


def parse_brand(path: Path) -> dict:
    """Parse the flat YAML subset into {section: {key: value}}."""
    sections: dict = {}
    current = None
    for raw in path.read_text().splitlines():
        line = _strip_comment(raw).strip()
        if not line:
            continue
        if not line.startswith(" ") and line.endswith(":"):
            current = line[:-1].strip()
            sections[current] = {}
            continue
        if current is None:
            continue
        m = re.match(r"^([\w-]+):\s*(.+)$", line)
        if m:
            key, value = m.group(1), m.group(2).strip()
            value = re.sub(r'^"(.*)"$', r"\1", value)
            sections[current][key] = value
    return sections


def hex_only(value: str) -> str:
    """#121212 -> 121212 (LaTeX HTML colour needs no hash)."""
    return value.lstrip("#").upper()


def emit_tex(colors: dict, aliases: dict) -> str:
    lines = [
        "% SPDX-License-Identifier: MIT",
        "% Generated by tools/tokens.py from brand.yml. Do not edit by hand.",
        "% Re-run tools/tokens.py after changing the palette.",
    ]
    for name, value in colors.items():
        lines.append(r"\definecolor{%s}{HTML}{%s}" % (name, hex_only(value)))
    for legacy, semantic in aliases.items():
        if semantic in colors:
            lines.append(
                r"\definecolor{%s}{HTML}{%s}" % (legacy, hex_only(colors[semantic]))
            )
    return "\n".join(lines) + "\n"


def emit_scss(sections: dict) -> str:
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by tools/tokens.py from brand.yml. Do not edit by hand.",
        "// Re-run tools/tokens.py after changing the tokens.",
        "",
    ]
    colors = sections.get("color", {})
    for name, value in colors.items():
        lines.append("$token-%s: %s;" % (name, value))
    lines.append("")
    types = sections.get("type", {})
    for name, value in types.items():
        # Inline list [size, line-height] -> two SCSS variables.
        m = re.match(r"^\[([0-9.]+),\s*([0-9.]+)\]$", value)
        if m:
            size, lh = m.group(1), m.group(2)
            lines.append("$type-%s-size: %spx;" % (name, size))
            lines.append("$type-%s-line: %spx;" % (name, lh))
        else:
            lines.append("$type-%s: %s;" % (name, value))
    lines.append("")
    spacing = sections.get("spacing", {})
    for name, value in spacing.items():
        lines.append("$space-%s: %s;" % (name, value))
    return "\n".join(lines) + "\n"


def check_theme_roles(sections: dict, theme_path: Path) -> int:
    """Verify the light theme's literals match the semantic roles.

    The light theme uses literal values (Quarto evaluates the
    defaults section before file-level imports), so a drift guard is
    needed: this returns non-zero when theme.scss disagrees with
    brand.yml. Run with --check in CI.
    """
    roles = {
        "primary": "theme-obsidian",
        "secondary": "theme-obsidianl",
        "border": "theme-ruled",
        "surface": "theme-cream",
    }
    colors = sections.get("color", {})
    text = theme_path.read_text()
    bad = []
    for role, var in roles.items():
        expected = colors.get(role, "")
        m = re.search(
            r"^\$%s:\s*(#[0-9a-fA-F]{6})" % re.escape(var), text, re.MULTILINE
        )
        if not m:
            bad.append("%s: missing" % var)
        elif m.group(1).lower() != expected.lower():
            bad.append("%s: %s != %s" % (var, m.group(1), expected))
    for msg in bad:
        print("tokens.py check: %s" % msg, file=sys.stderr)
    return 1 if bad else 0


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check_only = "--check" in sys.argv

    brand_path = (
        Path(args[0])
        if args
        else Path(__file__).resolve().parent.parent
        / "_extensions"
        / "obsidian"
        / "brand.yml"
    )
    outdir = Path(args[1]) if len(args) > 1 else brand_path.parent

    sections = parse_brand(brand_path)
    colors = sections.get("color", {})
    if not colors:
        print("tokens.py: no color section found in %s" % brand_path, file=sys.stderr)
        return 1

    if check_only:
        return check_theme_roles(sections, outdir / "theme.scss")

    (outdir / "tokens.tex").write_text(emit_tex(colors, LEGACY_ALIASES))
    (outdir / "tokens.scss").write_text(emit_scss(sections))
    print("wrote %s and %s" % (outdir / "tokens.tex", outdir / "tokens.scss"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
