name: Dependabot keep current

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: Obsidian-Solutions/.github/.github/workflows/dependabot-update-branch.yml@c0f4b15212359e6ff4b0bb5e3baa50d5bbe34390