name: Dependabot keep current

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: Obsidian-Solutions/.github/.github/workflows/dependabot-update-branch.yml@4a484222a90ded0b2aaf3b2d4a177a41b253a312
